{
 "title": "Station History",
 "time": { "from": "2023-03-21T13:30:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "永吉松信路口 - 可借車輛",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\" at time zone 'Asia/Taipei', \navailable_spaces \nFROM bike_history \nWHERE station_id = 500112051 "
    }
   ]
  },
  {
   "title": "敦化基隆路口 - 可借車輛",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \n\"time\" at time zone 'Asia/Taipei', \navailable_spaces \nFROM bike_history \nWHERE station_id = 500101123 "
    }
   ]
  },
  {
   "title": "資料總數",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM bike_history "
    }
   ]
  }
 ]
}