{
 "title": "Station History",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "上班", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "永吉松信路口",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "station_500112051", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "富台公園",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "station_500112068", "legendFormat": "__auto" }
   ]
  },
  { "title": "下班", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "敦化基隆路口",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "station_500101123", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "國北教大側門南側",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "station_500101091" }
   ]
  },
  {
   "title": "和平敦化路口",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "station_500101192", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "敦化南路二段293巷口南側",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "station_500101122", "legendFormat": "__auto" }
   ]
  }
 ]
}